files = []

[player]
name = ""
skin = ""
color = 0

[game]
renderer = 0
windowmode = 0
music = 0
sound = 0
exepath = "srb2win.exe"
cliargs = ""

[host]
hostname = ""
password = ""
room = 0
gametype = 0
advancemap = 1
pointlimit = ""
timelimit = ""
maxplayers = ""
forceskin = ""
disableweaponrings = false
suddendeath = false
dedicated = false

[settings]
wine = false
theme = 0
includefiles = false

[game.resolution]
width = ""
height = ""
